--- CRIAÇÃO DA TABELAS
CREATE TABLE VEICULOS
(
placa CHAR(8),
ano NUMBER(4),
km NUMBER(6),
marca VARCHAR(50),
modelo VARCHAR(50)
);

--- INSERÇÃO DE DADOS
INSERT INTO VEICULOS
VALUES ('IJK-1212', 2022, 0, 'Chevrolet', 'Onix');
INSERT INTO VEICULOS (placa, ano, km, marca, modelo)
VALUES ('IJM-1556', 2015, 72045, 'Volkswagen', 'Gol');

Select ano, * from  VEICULOS V
Where V.ano < '2022'

--- UPDATE ---
UPDATE VEICULOS
SET modelo = 'Cruze'
WHERE placa = 'IJK-1212';

UPDATE VEICULOS
SET KM = 0
WHERE KM < 10;

--- DELETE ---
DELETE FROM VEICULOS
WHERE placa = 'IJM-1556'; 

DELETE FROM VEICULOS
WHERE (marca = 'Chevrolet') AND (km > 50000); -- DELETO TODOS DA MARCA CHEVROLET COM + DE 50000 KM

--- ORDER BY ---

SELECT placa, km
FROM VEICULOS
ORDER BY km;
SELECT placa, km
FROM VEICULOS
WHERE ano > 2000
ORDER BY km DESC; -- DECRESCENTE - MAIOR PARA MENOR

--- COUNT --- CONTANDO REGISTROS

SELECT COUNT(*)
FROM VEICULOS
WHERE km = 0;

SELECT COUNT(*) FROM VEICULOS
WHERE marca = 'Ford'

--- DISTINCT --- TRAZ OS REGISTRO DIFERENTES DA COLUNA

SELECT DISTINCT marca
FROM VEICULOS;

